services:
  db:
    image: postgres:15-alpine
    container_name: hermes_db
    restart: always
    environment:
      POSTGRES_DB: hermes_db
      POSTGRES_USER: hermes_user
      POSTGRES_PASSWORD: hermes_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: hermes_web
    restart: always
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=her-mes.uz,www.her-mes.uz,localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=https://her-mes.uz,https://www.her-mes.uz
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: hermes_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: hermes_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume: