# Generated by Django 5.2.9 on 2026-01-18 11:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('code', models.CharField(max_length=10, verbose_name='Kod')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['region', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('code', models.CharField(help_text='Masalan: TAS, SAM, BUX', max_length=10, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kod')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Aholi soni')),
                ('households', models.PositiveIntegerField(default=0, verbose_name='Xonadonlar soni')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mahallas', to='accounts.district', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('region_admin', 'Viloyat Admini'), ('district_admin', 'Tuman Admini'), ('leader', 'Mahalla Yetakchisi')], db_index=True, default='leader', max_length=20, verbose_name='Rol')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('blocked', 'Bloklangan'), ('pending', 'Kutilmoqda')], db_index=True, default='active', max_length=20, verbose_name='Holat')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998XXXXXXXXX', regex='^\\+998[0-9]{9}$')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Rasm')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Lavozimi')),
                ('bio', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('plain_password', models.CharField(blank=True, help_text="Faqat birinchi marta ko'rsatish uchun", max_length=50, verbose_name='Parol (ochiq)')),
                ('must_change_password', models.BooleanField(default=True, verbose_name="Parolni o'zgartirish kerak")),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Oxirgi IP')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Kirish soni')),
                ('notify_email', models.BooleanField(default=False, verbose_name='Email bildirishnoma')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='SMS bildirishnoma')),
                ('notify_web', models.BooleanField(default=True, verbose_name='Web bildirishnoma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.district', verbose_name='Tuman')),
                ('mahalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.mahalla', verbose_name='Mahalla')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task_new', 'Yangi vazifa'), ('task_deadline', 'Muddat yaqinlashdi'), ('task_overdue', "Muddat o'tdi"), ('task_approved', 'Vazifa tasdiqlandi'), ('task_rejected', 'Vazifa rad etildi'), ('announcement', "E'lon"), ('system', 'Tizim xabari'), ('warning', 'Ogohlantirish')], db_index=True, default='system', max_length=20, verbose_name='Turi')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=20, verbose_name='Muhimlik')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='accounts.region', verbose_name='Viloyat'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Matn')),
                ('priority', models.CharField(choices=[('low', 'Oddiy'), ('normal', "O'rta"), ('high', 'Muhim'), ('urgent', 'Shoshilinch')], default='normal', max_length=20, verbose_name='Muhimlik')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Holat')),
                ('target_all', models.BooleanField(default=True, verbose_name='Hammaga')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="['leader', 'district_admin']", verbose_name='Rollar')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name="E'lon vaqti")),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='Fayl')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('target_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.district', verbose_name='Tuman')),
                ('target_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mahalla',
            index=models.Index(fields=['district', 'is_active'], name='accounts_ma_distric_5de619_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'is_active'], name='accounts_di_region__2e9275_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'code')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='accounts_us_role_9fc6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['region', 'district'], name='accounts_us_region__87504e_idx'),
        ),
    ]
