# Generated by Django 5.2.9 on 2026-01-18 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998XXXXXXXXX', regex='^\\+998[0-9]{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
