# Generated by Django 5.2.9 on 2026-01-06 10:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, help_text="Vazifa haqida batafsil ma'lumot", verbose_name='Tavsif')),
                ('task_type', models.CharField(choices=[('survey', "📋 So'rovnoma"), ('excel', "📊 Excel to'ldirish"), ('report', "📝 Hisobot yig'ish"), ('mixed', '🔀 Aralash')], db_index=True, default='survey', max_length=20, verbose_name='Vazifa turi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('paused', "To'xtatilgan"), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=20, verbose_name='Holat')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], db_index=True, default='medium', max_length=20, verbose_name='Muhimlik')),
                ('deadline', models.DateTimeField(db_index=True, verbose_name='Muddat')),
                ('start_date', models.DateTimeField(blank=True, help_text="Bo'sh = darhol boshlanadi", null=True, verbose_name='Boshlanish')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='Eslatma yuborish')),
                ('reminder_hours', models.PositiveIntegerField(default=24, help_text='Muddat tugashiga necha soat qolganda', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Eslatma vaqti')),
                ('source_file', models.FileField(blank=True, help_text='Excel shablon fayl', null=True, upload_to='tasks/source/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls', 'csv'])], verbose_name='Yuklangan fayl')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='tasks/results/%Y/%m/', verbose_name='Natija fayl')),
                ('stats_total_assigned', models.PositiveIntegerField(default=0, verbose_name='Jami tayinlangan')),
                ('stats_total_seen', models.PositiveIntegerField(default=0, verbose_name="Ko'rganlar")),
                ('stats_total_started', models.PositiveIntegerField(default=0, verbose_name='Boshlaganlar')),
                ('stats_total_completed', models.PositiveIntegerField(default=0, verbose_name='Bajarganlar')),
                ('stats_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Bajarilish foizi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name="E'lon qilingan")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('notes', models.TextField(blank=True, help_text="Faqat adminlar ko'radi", verbose_name='Ichki eslatmalar')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('target_district', models.ForeignKey(blank=True, help_text="Bo'sh = barcha tumanlar", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.district', verbose_name='Tuman')),
                ('target_mahallas', models.ManyToManyField(blank=True, help_text="Bo'sh = barcha mahallalar", related_name='tasks', to='accounts.mahalla', verbose_name='Mahallalar')),
                ('target_region', models.ForeignKey(blank=True, help_text="Bo'sh = barcha viloyatlar", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('text', 'Matn'), ('number', 'Raqam'), ('choice', 'Tanlov'), ('multiple', "Ko'p tanlov"), ('yes_no', "Ha/Yo'q"), ('date', 'Sana'), ('phone', 'Telefon'), ('email', 'Email')], default='text', max_length=20, verbose_name='Javob turi')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('choices', models.JSONField(blank=True, help_text="['Variant 1', 'Variant 2', ...]", null=True, verbose_name='Variantlar')),
                ('validation', models.JSONField(blank=True, help_text="{'min': 0, 'max': 100, 'min_length': 10, 'regex': '^[0-9]+$'}", null=True, verbose_name='Tekshirish qoidalari')),
                ('error_message', models.CharField(blank=True, help_text="Noto'g'ri javob kiritilganda", max_length=255, verbose_name='Xatolik xabari')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Yordam matni')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='Placeholder')),
                ('excel_column', models.CharField(blank=True, help_text="Natija Excelda qaysi ustun nomi bo'ladi", max_length=100, verbose_name='Excel ustun nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['task', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Yuborildi'), ('seen', "Ko'rdi"), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('overdue', "Muddati o'tdi")], db_index=True, default='pending', max_length=20, verbose_name='Holat')),
                ('current_question_order', models.PositiveIntegerField(default=0, help_text='Yetakchi qaysi savolda turibdi', verbose_name='Joriy savol')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rilgan")),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('reminder_sent_count', models.PositiveIntegerField(default=0, verbose_name='Eslatmalar soni')),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi eslatma')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Yetakchi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Tayinlash',
                'verbose_name_plural': 'Tayinlashlar',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Raqam')),
                ('value_choice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tanlov')),
                ('value_multiple', models.JSONField(blank=True, null=True, verbose_name="Ko'p tanlov")),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name="Ha/Yo'q")),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('is_valid', models.BooleanField(default=True, verbose_name="To'g'ri")),
                ('validation_errors', models.JSONField(blank=True, null=True, verbose_name='Xatolar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.question', verbose_name='Savol')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.taskassignment', verbose_name='Tayinlash')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('published', "E'lon qilindi"), ('assigned', 'Tayinlandi'), ('seen', "Ko'rildi"), ('started', 'Boshlandi'), ('answered', 'Javob berildi'), ('completed', 'Yakunlandi'), ('reminder', 'Eslatma yuborildi'), ('edited', 'Tahrirlandi'), ('cancelled', 'Bekor qilindi')], db_index=True, max_length=20, verbose_name='Harakat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Eski qiymat')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Yangi qiymat')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_actions', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.taskassignment', verbose_name='Tayinlash')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Tarix',
                'verbose_name_plural': 'Tarix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='tasks_task_status_01b536_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-deadline'], name='tasks_task_status_6daa08_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='tasks_task_created_69a8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-deadline'], name='tasks_task_deadlin_b62103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('task', 'order')},
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task', 'status'], name='tasks_taska_task_id_d49859_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['leader', 'status'], name='tasks_taska_leader__14de6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'leader')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assignment', 'question')},
        ),
    ]
